//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLanguage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAW.UI.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri Dön.
        /// </summary>
        public static string EP_GO_BACK {
            get {
                return ResourceManager.GetString("EP_GO_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İç Sunucu Hatası.
        /// </summary>
        public static string EP_INTERNAL_SERVER_ERROR {
            get {
                return ResourceManager.GetString("EP_INTERNAL_SERVER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Bulunamadı.
        /// </summary>
        public static string EP_PAGE_NOT_FOUND {
            get {
                return ResourceManager.GetString("EP_PAGE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BU SAYFA KALDIRILMIŞ.
        /// </summary>
        public static string EP_THIS_PAGE_HAVE_BEEN_REMOVED {
            get {
                return ResourceManager.GetString("EP_THIS_PAGE_HAVE_BEEN_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEKLENMEDİK BİR HATA OLUŞTU.
        /// </summary>
        public static string EP_UNEXPECTED_ERROR_OCCURED {
            get {
                return ResourceManager.GetString("EP_UNEXPECTED_ERROR_OCCURED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkında.
        /// </summary>
        public static string LP_ABOUT {
            get {
                return ResourceManager.GetString("LP_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her Zaman Güvenli.
        /// </summary>
        public static string LP_ALWAYS_SECURE {
            get {
                return ResourceManager.GetString("LP_ALWAYS_SECURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailleriniz ve mesajlarınız üçüncü şahıslarla paylaşılmadan yönetici-çalışan arasında her daim güvenli iletişim sağlar..
        /// </summary>
        public static string LP_ALWAYS_SECURE_CONTEXT {
            get {
                return ResourceManager.GetString("LP_ALWAYS_SECURE_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herhangi bir sorunuz mu var? Direkt iletişime geçin..
        /// </summary>
        public static string LP_ANY_QUESTION_SENTENCE {
            get {
                return ResourceManager.GetString("LP_ANY_QUESTION_SENTENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başa dön.
        /// </summary>
        public static string LP_BACK_TO_TOP {
            get {
                return ResourceManager.GetString("LP_BACK_TO_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışanlarınızın çalışma saatlerini otomatik shift uygulaması ile hazırlayarak zamanı daha verimli kullanın.
        /// </summary>
        public static string LP_BANNER_CONTEXT {
            get {
                return ResourceManager.GetString("LP_BANNER_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışanlarınızla .
        /// </summary>
        public static string LP_BANNER_HEADER_1 {
            get {
                return ResourceManager.GetString("LP_BANNER_HEADER_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tek Bir Uygulamadan İletişim Kurun.
        /// </summary>
        public static string LP_BANNER_HEADER_2 {
            get {
                return ResourceManager.GetString("LP_BANNER_HEADER_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string LP_BLOG {
            get {
                return ResourceManager.GetString("LP_BLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajlaşma.
        /// </summary>
        public static string LP_CHAT {
            get {
                return ResourceManager.GetString("LP_CHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici ile çalışanların tek bir uygulama içerisinde hızlıca iletişim kurabilmelerini sağlar..
        /// </summary>
        public static string LP_CHAT_CONTEXT {
            get {
                return ResourceManager.GetString("LP_CHAT_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm hakları saklıdır..
        /// </summary>
        public static string LP_COPYRIGHT {
            get {
                return ResourceManager.GetString("LP_COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluştur.
        /// </summary>
        public static string LP_CREATE {
            get {
                return ResourceManager.GetString("LP_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsteğinize bağlı manuel veya otomatik bir şekilde çalışanlarınız için shift oluşturun..
        /// </summary>
        public static string LP_CREATE_CONTEXT {
            get {
                return ResourceManager.GetString("LP_CREATE_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UYGULAMAYI İNDİRİN.
        /// </summary>
        public static string LP_DOWNLOAD_THE_APP {
            get {
                return ResourceManager.GetString("LP_DOWNLOAD_THE_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulamayı Hemen İndirin!.
        /// </summary>
        public static string LP_DOWNLOAD_THE_APP_NOW {
            get {
                return ResourceManager.GetString("LP_DOWNLOAD_THE_APP_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta.
        /// </summary>
        public static string LP_EMAIL {
            get {
                return ResourceManager.GetString("LP_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Adresi.
        /// </summary>
        public static string LP_EMAIL_ADRESS {
            get {
                return ResourceManager.GetString("LP_EMAIL_ADRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tek bir uygulama ile kurumsal E-postalarınızı iletmenizi sağlar..
        /// </summary>
        public static string LP_EMAIL_CONTEXT {
            get {
                return ResourceManager.GetString("LP_EMAIL_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hızlı..
        /// </summary>
        public static string LP_FASTER {
            get {
                return ResourceManager.GetString("LP_FASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tek tıkla haftalık çalışma programını hazırlar ve anında erişim sağlar..
        /// </summary>
        public static string LP_FASTER_CONTEXT {
            get {
                return ResourceManager.GetString("LP_FASTER_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özellikler.
        /// </summary>
        public static string LP_FEATURES {
            get {
                return ResourceManager.GetString("LP_FEATURES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string LP_HOME {
            get {
                return ResourceManager.GetString("LP_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama Nasıl Çalışır?.
        /// </summary>
        public static string LP_HOW_THE_APP_WORKS {
            get {
                return ResourceManager.GetString("LP_HOW_THE_APP_WORKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro.
        /// </summary>
        public static string LP_INTRO {
            get {
                return ResourceManager.GetString("LP_INTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arayı Soğutmayalım..
        /// </summary>
        public static string LP_LETS_STAY_IN_TOUCH {
            get {
                return ResourceManager.GetString("LP_LETS_STAY_IN_TOUCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncellemeler, özel teklifler ve daha fazlası için abone olun..
        /// </summary>
        public static string LP_LETS_STAY_IN_TOUCH_CONTENT {
            get {
                return ResourceManager.GetString("LP_LETS_STAY_IN_TOUCH_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönet.
        /// </summary>
        public static string LP_MANAGE {
            get {
                return ResourceManager.GetString("LP_MANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgisayar, tablet ve mobil cihazlarınızdan dilediğiniz zamanda ve dilediğiniz yerden işletmenizi yönetin..
        /// </summary>
        public static string LP_MANAGE_CONTEXT {
            get {
                return ResourceManager.GetString("LP_MANAGE_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetilebilir..
        /// </summary>
        public static string LP_MANAGEABLE {
            get {
                return ResourceManager.GetString("LP_MANAGEABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışan giriş çıkışları, izinleri vs. gibi birçok olayı kontrol etmek daha kolay hale gelir..
        /// </summary>
        public static string LP_MANAGEABLE_CONTEXT {
            get {
                return ResourceManager.GetString("LP_MANAGEABLE_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İhtiyacınıza Göre Üyelik Seçenekleri.
        /// </summary>
        public static string LP_MEMBERSHIP {
            get {
                return ResourceManager.GetString("LP_MEMBERSHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İhtiyaç ve isteklerinize göre biçimlendirilen üyelik paketlerimizi 3 aylık deneme paketi şeklinde ya da 1 yıllık, 5 yılllık, 10 yıllık paketler şeklinde satın alabilirsiniz..
        /// </summary>
        public static string LP_MEMBERSHIP_CONTENT {
            get {
                return ResourceManager.GetString("LP_MEMBERSHIP_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirimler.
        /// </summary>
        public static string LP_NOTIFICATION {
            get {
                return ResourceManager.GetString("LP_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anında paylaştığınız verilerden, tablolardan, taslaklardan bildirimler sayesinde haberiniz olur..
        /// </summary>
        public static string LP_NOTIFICATION_CONTEXT {
            get {
                return ResourceManager.GetString("LP_NOTIFICATION_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ücretlendirme.
        /// </summary>
        public static string LP_PRICING {
            get {
                return ResourceManager.GetString("LP_PRICING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aşağı Kaydırın.
        /// </summary>
        public static string LP_SCROLL_DOWN {
            get {
                return ResourceManager.GetString("LP_SCROLL_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenli..
        /// </summary>
        public static string LP_SECURE {
            get {
                return ResourceManager.GetString("LP_SECURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışan ve yöneticilerin bilgilerini saklı tutar. Kişisel ve şirket verilerinin korunması ilkesiyle çalışır..
        /// </summary>
        public static string LP_SECURE_CONTEXT {
            get {
                return ResourceManager.GetString("LP_SECURE_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paylaş.
        /// </summary>
        public static string LP_SHARE {
            get {
                return ResourceManager.GetString("LP_SHARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tek tıkla tüm duyurularınızı çalışanlarınızla anında paylaşın..
        /// </summary>
        public static string LP_SHARE_CONTEXT {
            get {
                return ResourceManager.GetString("LP_SHARE_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string LP_SIGN_IN {
            get {
                return ResourceManager.GetString("LP_SIGN_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistem tarafından oluşturulmuş bilgilerinizle hızlıca sisteme giriş yapın..
        /// </summary>
        public static string LP_SIGN_IN_CONTEXT {
            get {
                return ResourceManager.GetString("LP_SIGN_IN_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akıllı..
        /// </summary>
        public static string LP_SMART {
            get {
                return ResourceManager.GetString("LP_SMART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birden fazla parametreyi kullanarak sizin gibi düşünür ve ona göre shift hazırlar..
        /// </summary>
        public static string LP_SMART_CONTEXT {
            get {
                return ResourceManager.GetString("LP_SMART_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abone Ol.
        /// </summary>
        public static string LP_SUBSCRIBE {
            get {
                return ResourceManager.GetString("LP_SUBSCRIBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7/24 Destek.
        /// </summary>
        public static string LP_SUPPORT {
            get {
                return ResourceManager.GetString("LP_SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7/24 sistemsel sorunlarınızı çözümlüyor ve size yardımcı olmak için mail ve canlı destek hattından yardımcı oluyoruz. Ayrıca sisteminizi güncel tutarak gerekli bakım ve onarımları gerçekleştiriyoruz..
        /// </summary>
        public static string LP_SUPPORT_CONTENT {
            get {
                return ResourceManager.GetString("LP_SUPPORT_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kesinlikle Seveceğiniz Özellikler ile Hazırlandı..
        /// </summary>
        public static string LP_SURELY_LOVE_FEATURES {
            get {
                return ResourceManager.GetString("LP_SURELY_LOVE_FEATURES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici ve çalışanların hızlı bir şekilde entegre olmasını sağlayarak iş planlama performansının üst düzeyde tutulmasını sağlar. Değişen plan veya duyurulardan anında  haberiniz olur..
        /// </summary>
        public static string LP_SURELY_LOVE_FEATURES_CONTEXT {
            get {
                return ResourceManager.GetString("LP_SURELY_LOVE_FEATURES_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Popüler Ve 1 Numaralı Shift Uygulaması.
        /// </summary>
        public static string LP_THE_MOST_POPULAR_SHIFTER_APP {
            get {
                return ResourceManager.GetString("LP_THE_MOST_POPULAR_SHIFTER_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullandıkça zamanınızı daha verimli, yönetilebilir ve çalışanlarınızın iş için sürekli kullandığı bir platforma sahip olacaksınız..
        /// </summary>
        public static string LP_THE_MOST_POPULAR_SHIFTER_APP_CONTEXT {
            get {
                return ResourceManager.GetString("LP_THE_MOST_POPULAR_SHIFTER_APP_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Dostu..
        /// </summary>
        public static string LP_USER_FRIENDLY {
            get {
                return ResourceManager.GetString("LP_USER_FRIENDLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basit kullanıcı arayüzleri ile kolay öğrenilip istenilen her yerden ulaşılarak kullanılabilir..
        /// </summary>
        public static string LP_USER_FRIENDLY_CONTEXT {
            get {
                return ResourceManager.GetString("LP_USER_FRIENDLY_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shifter and Worker..
        /// </summary>
        public static string PROJECT_NAME {
            get {
                return ResourceManager.GetString("PROJECT_NAME", resourceCulture);
            }
        }
    }
}
