//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAW.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.Stores = new HashSet<Store>();
        }
    
        public int AddressId { get; set; }
        public string Address1 { get; set; }
        public string AddressType { get; set; }
        public int ZipCode { get; set; }
        public int ProvinceId { get; set; }
        public int TownId { get; set; }
        public int RegionId { get; set; }
    
        public virtual Province Province { get; set; }
        public virtual Region Region { get; set; }
        public virtual Town Town { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Store> Stores { get; set; }
    }
}
