//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAW.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Announcement()
        {
            this.UserAnnouncements = new HashSet<UserAnnouncement>();
        }
    
        public int AnnouncementId { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public bool IsImportant { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatorId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAnnouncement> UserAnnouncements { get; set; }
    }
}
