//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAW.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftBreak
    {
        public int ShiftBreakId { get; set; }
        public int ShiftId { get; set; }
        public int BreakId { get; set; }
    
        public virtual Break Break { get; set; }
        public virtual Shift Shift { get; set; }
    }
}
