//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAW.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAnnouncement
    {
        public int UserAnnouncementId { get; set; }
        public int UserId { get; set; }
        public int AnnouncementId { get; set; }
        public bool IsRead { get; set; }
    
        public virtual Announcement Announcement { get; set; }
        public virtual User User { get; set; }
    }
}
